version: '2'
services:
  trails:
    build: .
    command: supervisord -n
    volumes:
      - ./code:/code
      - ./www:/var/www
      - ./nginx-sites-available:/etc/nginx/sites-available
      - ./supervisor-confd:/etc/supervisor/conf.d
    ports:
      - "80:80"
    container_name: trails
